local configs = require("nvim-treesitter.configs")
configs.setup {
  ensure_installed = "all",
  sync_install = true,
  ignore_install = {
    "c_sharp",
    "agda",
    "astro",
    "beancount",
    "bibltex",
    "clojure",
    "commonlisp",
    "cooklang",
    "d",
    "dart",
    "devicetree",
    "eex",
    "elixir",
    "elvish",
    "erlang",
    "fennel",
    "foam",
    "fusion",
    "fortran",
    "gdscript",
    "gleam",
    "Glimmer and Ember",
    "gdresource",
    "hack",
    "haskell",
    "hcl",
    "heex",
    "hocon",
    "lalroop",
    "ledger",
    "m68k",
    "menhir",
    "norg",
    "ocaml",
    "ocaml_interface",
    "ocamllex",
    "pascal",
    "perl",
    "php",
    "phpdoc",
    "pioasm",
    "prisma",
    "proto",
    "pug",
    "ql",
    "qmljs",
    "r",
    "racket",
    "rego",
    "rnoweb",
    "scala",
    "scheme",
    "supercollider",
    "surface",
    "swift",
    "sxhkdrc",
    "teal",
    "turtle",
    "v",
    "vala",
    "wgsl",
    "yang",
  }, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { "" }, -- list of language that will be disabled
    additional_vim_regex_highlighting = true,

  },
  indent = { enable = true, disable = { "yaml" } },
  rainbow = { enable = true },
  contex_commentstring = { enable = true, enable_autocmd = false},
}
